analytics:
  google:
    id: UA-101217570-1


repository: cainiuwow/Falin-Navigation
repository_url: https://github.com/cainiuwow/Falin-Navigation

timezone: Asia/Shanghai

name: 法林导航 · Falin-Navi
author: 张明浩
author_url: http://cainiu.de
description: 专注于提高法律人的工作效率
keywords: 法林导航, Falin-Navi, 法林, 导航, Navi, Navigation
url: https://falin.xyz
contact: i[at]falin[dot]xyz

logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

gems:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor